### PR TITLE
Make the bull queue library a soft dependency

### PR DESCRIPTION
**Pull request by airhorns**
## Description of the change

For applications which don't use the `bull`-based persistent event queueing system, rudderstack-sdk-node still installs and requires the module. `bull` is kind of heavyweight -- it includes a bunch of redis dependencies and a `msgpackr` library which has a native extension. For my app this native extension has been rather annoying to keep support for despite us not using it at all.

I think it'd be a better default to not require the `bull` library until the sdk actually needs it to improve startup time, and if you folks are open to it, not listing it as a dependency in `package.json` as it is really an optional dependency. The docs would have to be updated to note that users who wanted to use the persistent queue would need to install `bull` separately. I don't think that's too wild.

Also, fwiw, bull has been deprecated in favour of `bullmq` which is a bit better supported these days, which is maybe another reason not to pull it into all users' apps.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

N/A

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [X]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by airhorns** [comment]
ping @saikumarrs it'd be great to get this in!

**Comment by saikumarrs** [comment]
@airhorns Thanks for the PR and the suggestion. We'll review this internally.
However, this would be a breaking change for pretty much most of the users. So, we'll have to execute this carefully. Please allow us some time.

**Comment by airhorns** [comment]
We could make it a non-breaking change by still including the dependency in the package.json and then removing it from there in the next major version if you like.

**Comment by MoumitaM** [comment]
Hi @airhorns, We are doing quarterly updates and maintenance of Node SDK. We have added bull as an optional dependency and this change will be reflected in the next release.

**Comment by MoumitaM** [comment]
Hi @airhorns, We released a new version of the SDK where the Bull dependency is updated to an optional dependency. You can run `npm install @rudderstack/rudder-sdk-node --no-optional` to avoid loading Bull.

**Comment by airhorns** [comment]
Great, thanks!

**Pull request closed without merging**
